version: '3.1'

services:
  server:
    build:
      context: ./server
    restart: always
    ports:
      - "3000:3000"

  db:
    image: postgres:14.2-alpine3.15
    restart: always
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
